name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Format BE
        run: npx prettier --list-different --plugin=prettier-plugin-solidity 'backend/contracts/**/*.sol'

      - name: Lint FE
        run: npx eslint .

      - name: Build BE
        run: pnpm run build:be

      - name: Build FE
        run: pnpm run build:fe
