name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Format BE
        run: npx prettier --list-different --plugin=prettier-plugin-solidity 'backend/contracts/**/*.sol'

      - name: Lint FE
        run: npx eslint .

  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build BE
        run: pnpm run be:build

      - uses: Sauloxd/review-apps@v2.0.0
        with:
          branch: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          apps: |
            {
              "app":{
                "build": "pnpm run fe:build",
                "dist": "frontend/dist"
              },
              "docs":{
                "build": "pnpm run docs:build",
                "dist": "docs/.vitepress/dist"
              }
            }
